version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - copyloopvar
    - dupl
    - errcheck
    - ginkgolinter
    - goconst
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - modernize
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    revive:
      rules:
        - name: comment-spacings
        - name: import-shadowing
    modernize:
      disable:
        - omitzero
    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Printf
        - fmt.Println
        - fmt.Fprintf
        - fmt.Fprintln
        - fmt.Print
    gosec:
      severity: high
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gosec
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
