# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy
    - ./scripts/completions.sh

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s"
      - "-w"
      - "-X github.com/idebeijer/kubert/pkg/versions.Version={{ .Version }}"
      - "-X github.com/idebeijer/kubert/pkg/versions.Commit={{ .ShortCommit }}"
      - "-X github.com/idebeijer/kubert/pkg/versions.Date={{ .Date }}"
      - "-X github.com/idebeijer/kubert/pkg/versions.BuiltBy=goreleaser"

archives:
  - id: completions
    files:
      - completions/*

homebrew_casks:
  - repository:
      owner: idebeijer
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/idebeijer/kubert"
    completions:
      bash: completions/kubert.bash
      zsh: completions/kubert.zsh
      fish: completions/kubert.fish
    hooks:
      post:
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kubert"]
          end

release:
  footer: |
    **Full Changelog**: https://github.com/idebeijer/kubert/compare/{{ .PreviousTag }}...{{ .Tag }}

changelog:
  sort: asc
  use: github
  groups:
    - title: "Breaking changes"
      regexp: '^.*?\w+(\(.+\))?!:\s?.+$'
      order: 0
    - title: "Features"
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 1
    - title: "Bug fixes"
      regexp: '^.*?fix(\(.+\))??!?:.+$'
      order: 2
    - title: "Documentation"
      regexp: '^.*?docs(\(.+\))??!?:.+$'
      order: 3
    - title: "Build system"
      regexp: '^.*?(build|ci)(\(.+\))??!?:.+$'
      order: 4
    - title: "Others"
      order: 999
  filters:
    exclude:
      - '^.*?(test|style)(\(.+\))??!?:.+$'
      - 'initial commit'