package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"

	"github.com/idebeijer/kubert/internal/kubert"
)

// bashInitScript is sourced via: eval "$(kubert shell-init bash)"
const bashInitScript = `# kubert shell integration for bash — generated by "kubert shell-init bash"
# Add to ~/.bashrc:
#   eval "$(kubert shell-init bash)"

export KUBERT_SHELL_INIT=1
export KUBERT_SHELL_INIT_SHELL=bash

kubert() {
  command kubert "$@"
  local _ec=$?
  local _f="/tmp/kubert-env-$$"
  if [[ -f "$_f" ]]; then
    # shellcheck source=/dev/null
    source "$_f" && rm -f "$_f"
  fi
  return $_ec
}
`

// zshInitScript is sourced via: eval "$(kubert shell-init zsh)"
const zshInitScript = `# kubert shell integration for zsh — generated by "kubert shell-init zsh"
# Add to ~/.zshrc:
#   eval "$(kubert shell-init zsh)"

export KUBERT_SHELL_INIT=1
export KUBERT_SHELL_INIT_SHELL=zsh

kubert() {
  command kubert "$@"
  local _ec=$?
  local _f="/tmp/kubert-env-$$"
  if [[ -f "$_f" ]]; then
    source "$_f" && rm -f "$_f"
  fi
  return $_ec
}
`

// fishInitScript is sourced via: kubert shell-init fish | source
const fishInitScript = `# kubert shell integration for fish — generated by "kubert shell-init fish"
# Add to ~/.config/fish/config.fish:
#   kubert shell-init fish | source

set -gx KUBERT_SHELL_INIT 1
set -gx KUBERT_SHELL_INIT_SHELL fish

function kubert
  command kubert $argv
  set _ec $status
  set _f /tmp/kubert-env-$fish_pid
  if test -f $_f
    source $_f && rm -f $_f
  end
  return $_ec
end
`

func NewShellInitCommand() *cobra.Command {
	return &cobra.Command{
		Use:   "shell-init [bash|zsh|fish]",
		Short: "Print shell integration script for the given shell",
		Long: `Print a shell function that wraps the kubert binary.

Source it once in your shell rc file so that env vars like KUBERT_SHELL_CONTEXT
are kept accurate after in-place context switches.

  bash/zsh:  eval "$(kubert shell-init bash)"
  fish:      kubert shell-init fish | source

If no shell is given, kubert attempts to detect it from $SHELL.`,
		Args:         cobra.MaximumNArgs(1),
		SilenceUsage: true,
		RunE: func(cmd *cobra.Command, args []string) error {
			shell, err := resolveShell(args)
			if err != nil {
				return err
			}
			switch shell {
			case "bash":
				fmt.Fprint(cmd.OutOrStdout(), bashInitScript)
			case "zsh":
				fmt.Fprint(cmd.OutOrStdout(), zshInitScript)
			case "fish":
				fmt.Fprint(cmd.OutOrStdout(), fishInitScript)
			}
			return nil
		},
	}
}

func resolveShell(args []string) (string, error) {
	if len(args) == 1 {
		return validateShell(args[0])
	}
	// Auto-detect from $SHELL
	shellBin := filepath.Base(os.Getenv("SHELL"))
	return validateShell(shellBin)
}

func validateShell(name string) (string, error) {
	switch name {
	case "bash", "zsh", "fish":
		return name, nil
	default:
		return "", fmt.Errorf("unsupported shell %q — supported: bash, zsh, fish", name)
	}
}

// envUpdateFilePath returns the path of the env-update file that the shell
// function will source after an in-place context switch.
// Uses /tmp directly so the path is identical whether computed by the Go binary
// or by the shell function's $$ variable.
func envUpdateFilePath(shellPID int) string {
	return fmt.Sprintf("/tmp/kubert-env-%d", shellPID)
}

// writeEnvUpdateFile writes updated KUBERT_SHELL_* vars to a file that the
// shell function sources after kubert returns.
func writeEnvUpdateFile(contextName, originalKubeconfigPath string) error {
	shell := os.Getenv(kubert.ShellInitShellEnvVar)
	path := envUpdateFilePath(os.Getppid())

	var sb strings.Builder
	if shell == "fish" {
		fmt.Fprintf(&sb, "set -gx %s %s\n", kubert.ShellContextEnvVar, fishQuote(contextName))
		fmt.Fprintf(&sb, "set -gx %s %s\n", kubert.ShellOriginalKubeconfigEnvVar, fishQuote(originalKubeconfigPath))
	} else {
		fmt.Fprintf(&sb, "export %s=%s\n", kubert.ShellContextEnvVar, shellSingleQuote(contextName))
		fmt.Fprintf(&sb, "export %s=%s\n", kubert.ShellOriginalKubeconfigEnvVar, shellSingleQuote(originalKubeconfigPath))
	}

	return os.WriteFile(path, []byte(sb.String()), 0600)
}

// shellSingleQuote wraps s in single quotes, safe for bash and zsh.
func shellSingleQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// fishQuote wraps s in double quotes, escaping characters special to fish.
func fishQuote(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	s = strings.ReplaceAll(s, `$`, `\$`)
	return `"` + s + `"`
}
