package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"

	"github.com/idebeijer/kubert/internal/kubert"
)

const (
	shellBash = "bash"
	shellZsh  = "zsh"
	shellFish = "fish"
)

// bashInitScript is sourced via: eval "$(kubert shell-init bash)"
const bashInitScript = `# kubert shell integration for bash — generated by "kubert shell-init bash"
# Add to ~/.bashrc:
#   eval "$(kubert shell-init bash)"

export KUBERT_SHELL_INIT=1
export KUBERT_SHELL_INIT_SHELL=bash

kubert() {
  command kubert "$@"
  local _ec=$?
  local _d="${XDG_RUNTIME_DIR:-${TMPDIR:-/tmp}}"
  local _f="${_d}/kubert-env-$$"
  if [[ -f "$_f" ]]; then
    # shellcheck source=/dev/null
    source "$_f"
    rm -f "$_f"
  fi
  return $_ec
}
`

// zshInitScript is sourced via: eval "$(kubert shell-init zsh)"
const zshInitScript = `# kubert shell integration for zsh — generated by "kubert shell-init zsh"
# Add to ~/.zshrc:
#   eval "$(kubert shell-init zsh)"

export KUBERT_SHELL_INIT=1
export KUBERT_SHELL_INIT_SHELL=zsh

kubert() {
  command kubert "$@"
  local _ec=$?
  local _d="${XDG_RUNTIME_DIR:-${TMPDIR:-/tmp}}"
  local _f="${_d}/kubert-env-$$"
  if [[ -f "$_f" ]]; then
    source "$_f"
    rm -f "$_f"
  fi
  return $_ec
}
`

// fishInitScript is sourced via: kubert shell-init fish | source
const fishInitScript = `# kubert shell integration for fish — generated by "kubert shell-init fish"
# Add to ~/.config/fish/config.fish:
#   kubert shell-init fish | source

set -gx KUBERT_SHELL_INIT 1
set -gx KUBERT_SHELL_INIT_SHELL fish

function kubert
  command kubert $argv
  set _ec $status
  set _d "$XDG_RUNTIME_DIR"
  test -z "$_d"; and set _d "$TMPDIR"
  test -z "$_d"; and set _d /tmp
  set _f "$_d/kubert-env-$fish_pid"
  if test -f $_f
    source $_f
    rm -f $_f
  end
  return $_ec
end
`

func NewShellInitCommand() *cobra.Command {
	return &cobra.Command{
		Use:   "shell-init [bash|zsh|fish]",
		Short: "Print optional shell integration script for the given shell",
		Long: `Print an optional shell function that wraps the kubert binary. (not required for core functionality)

Optionally source it once in your shell rc file so that env vars like KUBERT_SHELL_CONTEXT
are kept accurate after in-place context switches.

  bash/zsh:  eval "$(kubert shell-init bash)"
  fish:      kubert shell-init fish | source

If no shell is given, kubert attempts to detect it from $SHELL.`,
		Args:         cobra.MaximumNArgs(1),
		SilenceUsage: true,
		RunE: func(cmd *cobra.Command, args []string) error {
			shell, err := resolveShell(args)
			if err != nil {
				return err
			}
			switch shell {
			case shellBash:
				fmt.Fprint(cmd.OutOrStdout(), bashInitScript)
			case shellZsh:
				fmt.Fprint(cmd.OutOrStdout(), zshInitScript)
			case shellFish:
				fmt.Fprint(cmd.OutOrStdout(), fishInitScript)
			}
			return nil
		},
	}
}

func resolveShell(args []string) (string, error) {
	if len(args) == 1 {
		return validateShell(args[0])
	}
	// Auto-detect from $SHELL
	shellBin := filepath.Base(os.Getenv("SHELL"))
	return validateShell(shellBin)
}

func validateShell(name string) (string, error) {
	switch name {
	case shellBash, shellZsh, shellFish:
		return name, nil
	default:
		return "", fmt.Errorf("unsupported shell %q — supported: bash, zsh, fish", name)
	}
}

// envUpdateFilePath returns the path of the env-update file that the shell
// function will source after an in-place context switch.
// Priority: XDG_RUNTIME_DIR (user-owned, 0700) > TMPDIR > /tmp.
// Must match the lookup order in the generated shell scripts.
func envUpdateFilePath(shellPID int) string {
	for _, v := range []string{"XDG_RUNTIME_DIR", "TMPDIR"} {
		if dir := os.Getenv(v); dir != "" {
			return filepath.Join(dir, fmt.Sprintf("kubert-env-%d", shellPID))
		}
	}
	return filepath.Join("/tmp", fmt.Sprintf("kubert-env-%d", shellPID))
}

// writeEnvUpdateFile writes updated KUBERT_SHELL_* vars to a file that the
// shell function sources after kubert returns. The write is atomic (temp file
// + rename) to avoid partial reads by the shell.
func writeEnvUpdateFile(contextName, originalKubeconfigPath string) error {
	shell := os.Getenv(kubert.ShellInitShellEnvVar)
	path := envUpdateFilePath(os.Getppid())
	dir := filepath.Dir(path)

	var sb strings.Builder
	if shell == shellFish {
		fmt.Fprintf(&sb, "set -gx %s %s\n", kubert.ShellContextEnvVar, fishQuote(contextName))
		fmt.Fprintf(&sb, "set -gx %s %s\n", kubert.ShellOriginalKubeconfigEnvVar, fishQuote(originalKubeconfigPath))
	} else {
		fmt.Fprintf(&sb, "export %s=%s\n", kubert.ShellContextEnvVar, shellSingleQuote(contextName))
		fmt.Fprintf(&sb, "export %s=%s\n", kubert.ShellOriginalKubeconfigEnvVar, shellSingleQuote(originalKubeconfigPath))
	}

	tmp, err := os.CreateTemp(dir, "kubert-env-tmp-*")
	if err != nil {
		return fmt.Errorf("failed to create env update file: %w", err)
	}
	tmpName := tmp.Name()
	if err := tmp.Chmod(0o600); err != nil {
		_ = tmp.Close()
		_ = os.Remove(tmpName)
		return err
	}
	if _, err := tmp.WriteString(sb.String()); err != nil {
		_ = tmp.Close()
		_ = os.Remove(tmpName)
		return fmt.Errorf("failed to write env update file: %w", err)
	}
	if err := tmp.Close(); err != nil {
		_ = os.Remove(tmpName)
		return fmt.Errorf("failed to close env update file: %w", err)
	}
	return os.Rename(tmpName, path)
}

// shellSingleQuote wraps s in single quotes, safe for bash and zsh.
func shellSingleQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// fishQuote wraps s in double quotes, escaping characters special to fish.
func fishQuote(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	s = strings.ReplaceAll(s, `$`, `\$`)
	return `"` + s + `"`
}
