name: goreleaser

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  check-pat:
    runs-on: ubuntu-latest
    steps:
      - name: Check if homebrew tap token is valid
        env:
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: token $HOMEBREW_TAP_GITHUB_TOKEN" https://api.github.com/user)
          if [ "$response" -ne 200 ]; then
            echo "PAT is invalid or expired"
            exit 1
          fi
          echo "PAT is valid"

  goreleaser:
    runs-on: ubuntu-latest
    needs: check-pat
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
