name: goreleaser

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  check-pat:
    runs-on: ubuntu-latest
    steps:
      - name: Check if homebrew tap token is valid
        env:
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
        run: |
          curl -f \
            -H "Authorization: token ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository_owner }}/homebrew-tap

  goreleaser:
    runs-on: ubuntu-latest
    needs: check-pat
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
